# Generated by Django 3.2.25 on 2025-07-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20250701_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='original_basket',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
